// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkP_dwKDbssU2AhSz3c_lk_mGUvvOJH4Q',
    appId: '1:1062848339605:web:a4be7069c06304fcf9459c',
    messagingSenderId: '1062848339605',
    projectId: 'whatsapp-backend-2f629',
    authDomain: 'whatsapp-backend-2f629.firebaseapp.com',
    storageBucket: 'whatsapp-backend-2f629.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBbiOGqrOlN-L9tR89836-qSdp4Qs8svU',
    appId: '1:1062848339605:android:279ac9ce044e903bf9459c',
    messagingSenderId: '1062848339605',
    projectId: 'whatsapp-backend-2f629',
    storageBucket: 'whatsapp-backend-2f629.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdQQk-gm_Uz6AZ52r9yqrJz-ZkiDyTwAs',
    appId: '1:1062848339605:ios:08a96ef9e07cce4df9459c',
    messagingSenderId: '1062848339605',
    projectId: 'whatsapp-backend-2f629',
    storageBucket: 'whatsapp-backend-2f629.appspot.com',
    iosClientId: '1062848339605-4fltd9qanplt31t4i6sh3ov6rr15u3pa.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsappApp',
  );
}
